services:
  - type: web
    name: terminal-portfolio
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: NAME
        sync: false
      - key: GITHUB_URL
        sync: false
      - key: LINKEDIN_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true 